engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  radon:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false

ratings:
  paths:
    - "**.py"
    - "**.js"

exclude_paths:
  - "node_modules/"
  - "static/build/"
  - "static/fonts/"
  - "static/js/bootstrap.js"
  - "static/js/lib/"
  - "scripts/"
  - "update_scripts/"
