version: '2'

services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    networks:
      app:
        aliases:
          - postgres
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    environment:
        POSTGRES_USER: communityshare
        POSTGRES_PASSWORD: communityshare

  server:
    build: .
    working_dir: /communityshare
    ports:
      - "5000:5000"
    networks:
      - app
    volumes:
      - .:/communityshare
    privileged: true

  npm:
    build: .
    command: npm install
    working_dir: /communityshare
    volumes:
      - .:/communityshare

  webpack:
    build: .
    command: /communityshare/node_modules/.bin/webpack --watch
    working_dir: /communityshare
    volumes:
      - .:/communityshare
    depends_on:
      - npm

networks:
  app:
